/**
 * Seed inicial desde inventario Excel (15 registros con datos).
 * Justificaciones y controles compensatorios redactados de forma corporativa.
 */
export const seedExcepciones = [
  {
    id: "EXC-CIB-001",
    tipo_excepcion: "Acceso herramientas IA",
    origen_solicitud: "Teams",
    jira_ticket_id: null,
    solicitante_email: "aprado@calier.com",
    activo_afectado: "CA-z23VIX1Fivkx (aprado@calier.com)",
    estado: "Cancelada",
    temporalidad: "Temporal",
    fecha_solicitud: "2026-07-16",
    fecha_revision: "2026-07-18",
    fecha_decision: "2026-07-16",
    aprobador_email: "ntorrents_sirt@kernpharma.com",
    justificacion:
      "Acceso puntual a ChatGPT para cancelar una suscripción PRO asociada a una cuenta de Calier y evitar cargos indebidos.",
    control_compensatorio:
      "Acceso limitado en tiempo y alcance; sin uso operativo de la herramienta. Se orientó al usuario hacia Copilot corporativo.",
  },
  {
    id: "EXC-CIB-002",
    tipo_excepcion: "Acceso herramientas IA",
    origen_solicitud: "Correo",
    jira_ticket_id: null,
    solicitante_email: "amorant@kernpharma.com",
    activo_afectado: "KP-RCnUlmmaTmWc (ssalvador@kernpharma.com)",
    estado: "Aprobada",
    temporalidad: "Temporal",
    fecha_solicitud: "2026-07-03",
    fecha_revision: "2027-01-13",
    fecha_decision: "2026-07-13",
    aprobador_email: "ntorrents_sirt@kernpharma.com",
    justificacion:
      "Necesidad de Marketing de evaluar iniciativas GEO en herramientas de IA de mercado (ChatGPT, Claude, Gemini) complementarias a Copilot.",
    control_compensatorio:
      "Desbloqueo solo en el equipo autorizado. Prohibido introducir datos confidenciales, personales o regulados. Revisión periódica del uso.",
  },
  {
    id: "EXC-CIB-003",
    tipo_excepcion: "Acceso herramientas IA",
    origen_solicitud: "Correo",
    jira_ticket_id: null,
    solicitante_email: "eanaya@calier.co",
    activo_afectado:
      "José Alejandro Castaño (CO-LEN-31); Rafael Burgos (CO-LEN-30); Juan Arturo De La Cruz (DO-DELL-09)",
    estado: "Aprobada",
    temporalidad: "Temporal",
    fecha_solicitud: "2026-07-01",
    fecha_revision: "2026-09-15",
    fecha_decision: "2026-07-02",
    aprobador_email: "ntorrents_sirt@kernpharma.com",
    justificacion:
      "Marketing Digital LATAM requiere ChatGPT, Gemini, Claude y Google Labs para producción creativa y soporte comercial con flujos ya implantados.",
    control_compensatorio:
      "Acceso temporal acotado a tres usuarios. No usar datos sensibles ni de pacientes. Revisión de necesidad y alternativas (p. ej. Copilot) antes de renovar.",
  },
  {
    id: "EXC-CIB-004",
    tipo_excepcion: "Dispositivo USB",
    origen_solicitud: "Jira",
    jira_ticket_id: "TICK-229468",
    solicitante_email: "ckorobka@pharmakern.pt",
    activo_afectado: "KP-P77l9Oq7XFXV (ckorobka)",
    estado: "Aprobada",
    temporalidad: "Temporal",
    fecha_solicitud: "2026-02-25",
    fecha_revision: "2027-01-13",
    fecha_decision: "2026-04-01",
    aprobador_email: "Otro (Sistemas)",
    justificacion:
      "Excepción USB para operación de la sala de videoconferencia en Portugal ante incidencias del dispositivo local.",
    control_compensatorio:
      "Uso restringido al puesto afectado. Revisar si puede limitarse a los USB de la sala. Validar necesidad en próxima revisión.",
  },
  {
    id: "EXC-CIB-005",
    tipo_excepcion: "Dispositivo USB",
    origen_solicitud: "Teams",
    jira_ticket_id: null,
    solicitante_email: "aserna@calier.es",
    activo_afectado: "CA-LTvengA1GgS0 (aserna)",
    estado: "Aprobada",
    temporalidad: "Permanente",
    fecha_solicitud: "2026-04-01",
    fecha_revision: "2027-04-01",
    fecha_decision: "2026-04-01",
    aprobador_email: "jcrodriguez_sirt@kernpharma.com",
    justificacion:
      "Perfil de técnico informático que requiere USB para pruebas, instalación de ISO y tareas de soporte.",
    control_compensatorio:
      "Autorización ligada al rol IT. Equipo con EDR activo. Revisión anual de la necesidad.",
  },
  {
    id: "EXC-CIB-006",
    tipo_excepcion: "Configuración técnica excepcional",
    origen_solicitud: "Jira",
    jira_ticket_id: "COR-6485",
    solicitante_email: "mesteban@calier.es",
    activo_afectado: "CA-ZdPUBEN8Z8gx",
    estado: "Cancelada",
    temporalidad: "Temporal",
    fecha_solicitud: "2026-07-17",
    fecha_revision: "2026-07-23",
    fecha_decision: "2026-07-17",
    aprobador_email: "jcrodriguez_sirt@kernpharma.com",
    justificacion:
      "Ajuste temporal de perfiles/filtrado para permitir el trabajo con Facebook Business sin bloqueos indebidos.",
    control_compensatorio:
      "Cambio acotado en el tiempo. Tras validar acceso correcto a Facebook, se retiró la excepción.",
  },
  {
    id: "EXC-CIB-007",
    tipo_excepcion: "Dispositivo USB",
    origen_solicitud: "Teams",
    jira_ticket_id: null,
    solicitante_email: "hortiz@calier.co",
    activo_afectado: "CO-DELL-65",
    estado: "Cancelada",
    temporalidad: "Temporal",
    fecha_solicitud: "2026-07-22",
    fecha_revision: "2026-07-23",
    fecha_decision: "2026-07-22",
    aprobador_email: "jcrodriguez_sirt@kernpharma.com",
    justificacion:
      "Acceso USB de un día para transferir PDFs y presentaciones necesarias para una actividad comercial.",
    control_compensatorio:
      "Vigencia de 24 horas. Sin uso posterior; excepción cerrada al finalizar la transferencia.",
  },
  {
    id: "EXC-CIB-008",
    tipo_excepcion: "Dispositivo USB",
    origen_solicitud: "Jira",
    jira_ticket_id: "CIB-585",
    solicitante_email: "fmartin_ext@calier.es",
    activo_afectado: "CA-LPXypIF09pSs",
    estado: "Aprobada",
    temporalidad: "Permanente",
    fecha_solicitud: "2026-07-23",
    fecha_revision: "2026-09-15",
    fecha_decision: "2026-07-23",
    aprobador_email: "jcrodriguez_sirt@kernpharma.com",
    justificacion:
      "Personal de Service Desk en Calier León necesita USB para carga de ISO y funciones de soporte técnico.",
    control_compensatorio:
      "Acceso asociado al rol de técnico. EDR activo. Revisión periódica de permanencia del acceso.",
  },
  {
    id: "EXC-CIB-009",
    tipo_excepcion: "Dispositivo USB",
    origen_solicitud: "Jira",
    jira_ticket_id: "CIB-587",
    solicitante_email: "gbravo@calier.es",
    activo_afectado: "CA-I2IGusFLNL6f",
    estado: "Aprobada",
    temporalidad: "Permanente",
    fecha_solicitud: "2026-07-23",
    fecha_revision: "2026-09-15",
    fecha_decision: "2026-07-24",
    aprobador_email: "jcrodriguez_sirt@kernpharma.com",
    justificacion:
      "Descarga de dataloggers de temperatura asociados a mercancía; requisito operativo de almacén y logística.",
    control_compensatorio:
      "Uso limitado a dispositivos de logística autorizados. Validación del responsable IT. Revisión periódica.",
  },
  {
    id: "EXC-CIB-010",
    tipo_excepcion: "Configuración técnica excepcional",
    origen_solicitud: "Correo",
    jira_ticket_id: null,
    solicitante_email: "eanaya@calier.co",
    activo_afectado: "panamericanpet.com",
    estado: "Aprobada",
    temporalidad: "Temporal",
    fecha_solicitud: "2026-07-27",
    fecha_revision: "2026-08-09",
    fecha_decision: "2026-07-27",
    aprobador_email: "jcrodriguez_sirt@kernpharma.com",
    justificacion:
      "Permitir la recepción de correo del dominio panamericanpet.com necesario para la operativa de TI LATAM.",
    control_compensatorio:
      "Excepción temporal de filtrado/antispam solo para ese dominio. Seguimiento con el proveedor hasta solución definitiva.",
  },
  {
    id: "EXC-CIB-011",
    tipo_excepcion: "Dispositivo USB",
    origen_solicitud: "Jira",
    jira_ticket_id: "CIB-596",
    solicitante_email: "palvarez@kernpharma.com",
    activo_afectado: "KP-zNnl4To6JMTl",
    estado: "Aprobada",
    temporalidad: "Permanente",
    fecha_solicitud: "2026-07-28",
    fecha_revision: "2027-01-28",
    fecha_decision: "2026-07-28",
    aprobador_email: "jcrodriguez_sirt@kernpharma.com",
    justificacion:
      "Acceso USB para actuaciones en farmacias en el marco de la actividad comercial del Gerente de Zona Noroeste.",
    control_compensatorio:
      "Uso exclusivo para actividad profesional en farmacias. EDR activo. Revisión semestral de la necesidad.",
  },
  {
    id: "EXC-CIB-012",
    tipo_excepcion: "Dispositivo USB",
    origen_solicitud: "Jira",
    jira_ticket_id: "CIB-608",
    solicitante_email: "dgarciar@kernpharma.com",
    activo_afectado: "KP-H4CSjvUmdyik",
    estado: "Aprobada",
    temporalidad: "Permanente",
    fecha_solicitud: "2026-07-30",
    fecha_revision: "2026-09-15",
    fecha_decision: "2026-07-30",
    aprobador_email: "jcrodriguez_sirt@kernpharma.com",
    justificacion:
      "Tras cambio de PC, se requiere USB para extracción de datos de equipos OT en el entorno de almacén.",
    control_compensatorio:
      "Acceso asociado a perfil de logística/OT. Supervisión del área. Revisión de permanencia en fecha prevista.",
  },
  {
    id: "EXC-CIB-013",
    tipo_excepcion: "Dispositivo USB",
    origen_solicitud: "Jira",
    jira_ticket_id: "CIB-631",
    solicitante_email: "svida@pharmakern.pt",
    activo_afectado: "PMK-PRT-013",
    estado: "Aprobada",
    temporalidad: "Temporal",
    fecha_solicitud: "2026-09-04",
    fecha_revision: "2026-09-15",
    fecha_decision: "2026-09-04",
    aprobador_email: "jcrodriguez_sirt@kernpharma.com",
    justificacion:
      "Uso de software en CD-ROM requerido por Regulatory Affairs (Pharmakern Portugal) para tareas de trabajo.",
    control_compensatorio:
      "Acceso limitado al puesto indicado. Confirmar con la usuaria el uso efectivo y retirar si ya no es necesario.",
  },
  {
    id: "EXC-CIB-014",
    tipo_excepcion: "Dispositivo USB",
    origen_solicitud: "Jira",
    jira_ticket_id: "CIB-634",
    solicitante_email: "aprado@calier.com; ltejera@calier.com.uy",
    activo_afectado: "CA-z23VlX1Fivkx; N-DIRTEC",
    estado: "Aprobada",
    temporalidad: "Temporal",
    fecha_solicitud: "2026-09-07",
    fecha_revision: "2026-09-15",
    fecha_decision: "2026-09-07",
    aprobador_email: "jcrodriguez_sirt@kernpharma.com",
    justificacion:
      "Acceso USB temporal para dos usuarios de producto/SSTT Internacional con el fin de preparar y realizar una presentación.",
    control_compensatorio:
      "Vigencia corta. Revisar y retirar accesos tras la actividad si no hay nueva necesidad.",
  },
  {
    id: "EXC-CIB-015",
    tipo_excepcion: "Dispositivo USB",
    origen_solicitud: "Jira",
    jira_ticket_id: "CIB-633",
    solicitante_email: "fcasillas@calier.es",
    activo_afectado: "CA-tGW9cjQ99Lku",
    estado: "Aprobada",
    temporalidad: "Permanente",
    fecha_solicitud: "2026-09-07",
    fecha_revision: "2026-11-24",
    fecha_decision: "2026-09-08",
    aprobador_email: "jcrodriguez_sirt@kernpharma.com",
    justificacion:
      "Acceso USB para convenciones y presentaciones; usuario con autorización previa de su responsable.",
    control_compensatorio:
      "Continuidad de autorización existente. EDR activo. Revisión al cierre de año.",
  },
];
